# ML-10 — Content Action Playbook

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Ranked actions + reason codes

*The queue: what to do first, and why, in words a human trusts.*

### Ranked Actions + Reason Codes

The action queue prioritizes webpages using the transparent baseline signals developed
in ML-07. Pages with high impressions, low CTR, and poor average position receive
higher action scores because they have visible search exposure but show signals that
may justify human review.

### Action priority

- **Refresh Immediately** — high impressions + low CTR + poor average position.
  These pages have multiple observed signals that make them high-priority review
  candidates.
- **Review Soon** — two of the three signals are present. These pages show enough
  evidence to justify review but have less combined evidence than the highest-priority
  group.
- **Monitor** — one signal is present. These pages should be watched rather than
  immediately changed.
- **No Action** — none of the baseline signals are present.

### Reason codes

- `HIGH_IMPRESSIONS` — the page has strong observed search visibility.
- `LOW_CTR` — the page receives impressions but has a relatively low observed
  click-through rate.
- `POOR_POSITION` — the observed average search position is relatively weak.

The queue is decision-support rather than an automatic instruction to change content.
A high score means that a page is worth reviewing first; it does not prove that a
refresh will improve performance.

In [6]:
# ---------------------------------------------------------
# Section 1: Ranked Actions + Reason Codes
# ---------------------------------------------------------

import os
import pandas as pd

# ---------------------------------------------------------
# Load the baseline action queue created in ML-07
# ---------------------------------------------------------

baseline_path = "../outputs/baseline_action_score.csv"

if not os.path.exists(baseline_path):
    raise FileNotFoundError(
        "baseline_action_score.csv was not found. "
        "Run Section 2 of ML-07 first to regenerate it."
    )

ranked_df = pd.read_csv(baseline_path)

print("=" * 60)
print("BASELINE ACTION QUEUE LOADED")
print("=" * 60)

print("Rows:", len(ranked_df))
print("Columns:", list(ranked_df.columns))


# ---------------------------------------------------------
# Check required columns
# ---------------------------------------------------------

required_columns = [
    "content_id",
    "action_score",
    "reason_code",
    "action_label"
]

missing_columns = [
    col
    for col in required_columns
    if col not in ranked_df.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

print("\nRequired columns check: PASS")


# ---------------------------------------------------------
# Rank the action queue
# ---------------------------------------------------------

action_priority = {
    "Refresh Immediately": 1,
    "Review Soon": 2,
    "Monitor": 3,
    "No Action": 4
}

ranked_df["priority_order"] = (
    ranked_df["action_label"]
    .map(action_priority)
)

ranked_df = (
    ranked_df
    .sort_values(
        ["priority_order", "action_score"],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)

ranked_df["rank"] = (
    ranked_df.index + 1
)


# ---------------------------------------------------------
# Display action counts
# ---------------------------------------------------------

print("\n" + "=" * 60)
print("ACTION SUMMARY")
print("=" * 60)

print(
    ranked_df["action_label"]
    .value_counts()
)


# ---------------------------------------------------------
# Display reason-code counts
# ---------------------------------------------------------

print("\n" + "=" * 60)
print("REASON CODE SUMMARY")
print("=" * 60)

print(
    ranked_df["reason_code"]
    .value_counts()
)


# ---------------------------------------------------------
# Show the highest-priority actions
# ---------------------------------------------------------

print("\n" + "=" * 60)
print("TOP 20 ACTIONS")
print("=" * 60)

display(
    ranked_df[
        [
            "rank",
            "content_id",
            "action_score",
            "reason_code",
            "action_label"
        ]
    ].head(20)
)

============================================================
BASELINE ACTION QUEUE LOADED
============================================================
Rows: 30000
Columns: ['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct', 'action_score', 'reason_code', 'action_label']

Required columns check: PASS

============================================================
ACTION SUMMARY
============================================================
action_label
Monitor                15820
Review Soon            10317
No Action               2525
Refresh Immediately     1338
Name: count, dtype: int64

============================================================
REASON CODE SUMMARY
============================================================
reason_code
LOW_CTR                                     14373
LOW_CTR; POOR_POSITION                       6694
HIGH_IMPRESSIONS; LOW_CTR                    3547
NONE                                         2525
HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION     1338
HIGH_IMPRESSIONS                             1016
POOR_POSITION                                 431
HIGH_IMPRESSIONS; POOR_POSITION                76
Name: count, dtype: int64

============================================================
TOP 20 ACTIONS
============================================================

,rank,content_id,action_score,reason_code,action_label
0,1,content_2cb567c3c89b,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
1,2,content_2dba2b1f9536,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
2,3,content_b28d1efd668f,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
3,4,content_813e88069237,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
4,5,content_ff94c9b6b411,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
5,6,content_66b4046cc144,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
6,7,content_a023517539fe,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
7,8,content_b511d4bc4ad2,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
8,9,content_f02b48f88241,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
9,10,content_05e9b4cd9ccf,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
10,11,content_0e70a832cb7a,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
11,12,content_40fb6f005d61,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
12,13,content_8b36799b7e44,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
13,14,content_7158cfbbc450,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
14,15,content_88d367c507a3,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
15,16,content_e752a4e03dd3,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
16,17,content_54baba704595,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
17,18,content_124763d39ca5,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
18,19,content_551fe371f51b,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
19,20,content_938ef57eab09,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately

## 2. Intended use and limits

*Who uses this, for what — and where it stops being valid.*

### Intended Use and Limits

### Intended use

This playbook is intended to help content teams prioritize which webpages should
be reviewed first. The ranked queue is decision-support: it organizes pages using
observed historical signals and provides a reason code for each recommendation.

The main users are content strategists, SEO analysts, and reviewers who can inspect
the page and its context before deciding whether any action is appropriate.

### What the recommendations mean

- **Refresh Immediately** — highest-priority review candidates based on the baseline
  signals.
- **Review Soon** — pages with multiple signals that justify human review.
- **Monitor** — pages with a single observed signal that may be worth watching.
- **No Action** — pages where the baseline signals do not currently indicate a
  review priority.

### Limits

The score does not prove that refreshing a page will improve performance. It is
based on historical aggregate signals from the available dataset and may miss
important factors such as recent content changes, seasonality, search-engine
changes, business priorities, or information not represented in the dataset.

The queue should therefore be used for prioritization and decision-support, not
as an automatic content-change system.

In [7]:
# ---------------------------------------------------------
# Section 2: Intended Use and Limits
# ---------------------------------------------------------

print("=" * 60)
print("INTENDED USE AND LIMITS")
print("=" * 60)

print("""
INTENDED USE
------------
The action queue is designed to help content teams prioritize
webpages for human review.

The queue provides decision-support using observed historical
signals and transparent reason codes.

ACTION LEVELS
-------------
Refresh Immediately : highest-priority review candidates
Review Soon          : multiple signals justify review
Monitor              : one observed signal is present
No Action            : no baseline priority signal is present

LIMITS
------
The score does not prove that refreshing a page will improve
future performance.

The baseline uses historical aggregate signals and may not
capture recent content changes, seasonality, search-engine
changes, business priorities, or other factors outside the
dataset.

Recommendations should therefore be reviewed by a human before
any content change is made.
""")

# ---------------------------------------------------------
# Verify action categories
# ---------------------------------------------------------

expected_actions = [
    "Refresh Immediately",
    "Review Soon",
    "Monitor",
    "No Action"
]

observed_actions = sorted(
    ranked_df["action_label"].dropna().unique()
)

print("=" * 60)
print("ACTION CATEGORY CHECK")
print("=" * 60)

print("Observed actions:")
print(observed_actions)

missing_actions = [
    action
    for action in expected_actions
    if action not in observed_actions
]

print("\nMissing expected actions:")
print(missing_actions)

if len(missing_actions) == 0:
    print("\nPASS: All expected action categories are present.")
else:
    print("\nWARNING: Some expected action categories are missing.")

============================================================
INTENDED USE AND LIMITS
============================================================

INTENDED USE
------------
The action queue is designed to help content teams prioritize
webpages for human review.

The queue provides decision-support using observed historical
signals and transparent reason codes.

ACTION LEVELS
-------------
Refresh Immediately : highest-priority review candidates
Review Soon          : multiple signals justify review
Monitor              : one observed signal is present
No Action            : no baseline priority signal is present

LIMITS
------
The score does not prove that refreshing a page will improve
future performance.

The baseline uses historical aggregate signals and may not
capture recent content changes, seasonality, search-engine
changes, business priorities, or other factors outside the
dataset.

Recommendations should therefore be reviewed by a human before
any content change is made.

============================================================
ACTION CATEGORY CHECK
============================================================
Observed actions:
['Monitor', 'No Action', 'Refresh Immediately', 'Review Soon']

Missing expected actions:
[]

PASS: All expected action categories are present.

## 3. Human review + the no-go list

*What a person must check before acting. What should never be automated.*

### Human Review + No-Go List

### Human review rules

A person should review a recommendation before taking any content action.

The reviewer should check:

- Whether the page is still relevant to the intended audience.
- Whether the content is already up to date.
- Whether recent changes or seasonal effects could explain the observed signals.
- Whether the recommendation makes sense for the page's search intent.
- Whether there are business or editorial reasons not represented in the dataset.

The reason code should be treated as an explanation of why the page was ranked,
not as proof that the recommended action is correct.

### No-Go List

The system should NOT automatically:

- Publish or rewrite content.
- Delete or redirect a webpage.
- Change titles, URLs, or metadata without human review.
- Make decisions based only on the action score.
- Treat the score as proof that a content change will improve performance.
- Override editorial, business, or compliance decisions.

In [8]:
# ---------------------------------------------------------
# Section 3: Human Review + No-Go List
# ---------------------------------------------------------

print("=" * 60)
print("HUMAN REVIEW + NO-GO LIST")
print("=" * 60)

# ---------------------------------------------------------
# Human review rules
# ---------------------------------------------------------

review_rules = [
    "Check whether the page is still relevant.",
    "Check whether the content is already up to date.",
    "Check for recent changes or seasonal effects.",
    "Check whether the recommendation matches search intent.",
    "Check for business or editorial context not in the dataset."
]

print("\nHUMAN REVIEW RULES")
print("-" * 60)

for number, rule in enumerate(review_rules, start=1):
    print(f"{number}. {rule}")

# ---------------------------------------------------------
# No-go actions
# ---------------------------------------------------------

no_go_actions = [
    "Automatically publish or rewrite content.",
    "Automatically delete or redirect a webpage.",
    "Automatically change titles, URLs, or metadata.",
    "Make decisions using only the action score.",
    "Treat the score as proof of future performance improvement.",
    "Override editorial, business, or compliance decisions."
]

print("\nNO-GO LIST")
print("-" * 60)

for number, action in enumerate(no_go_actions, start=1):
    print(f"{number}. DO NOT {action}")

# ---------------------------------------------------------
# Final human-review requirement
# ---------------------------------------------------------

print("\n" + "=" * 60)
print("REVIEW REQUIREMENT")
print("=" * 60)

print(
    "PASS: Recommendations require human review before content action."
)

============================================================
HUMAN REVIEW + NO-GO LIST
============================================================

HUMAN REVIEW RULES
------------------------------------------------------------
1. Check whether the page is still relevant.
2. Check whether the content is already up to date.
3. Check for recent changes or seasonal effects.
4. Check whether the recommendation matches search intent.
5. Check for business or editorial context not in the dataset.

NO-GO LIST
------------------------------------------------------------
1. DO NOT Automatically publish or rewrite content.
2. DO NOT Automatically delete or redirect a webpage.
3. DO NOT Automatically change titles, URLs, or metadata.
4. DO NOT Make decisions using only the action score.
5. DO NOT Treat the score as proof of future performance improvement.
6. DO NOT Override editorial, business, or compliance decisions.

============================================================
REVIEW REQUIREMENT
============================================================
PASS: Recommendations require human review before content action.

## 4. Monitoring / retrain triggers

*What would tell you the recommendations went stale?*

### Monitoring / Retrain Triggers

The recommendations should be reviewed periodically because the underlying
content signals and search environment can change over time.

### Monitoring triggers

The playbook should be reviewed when:

- The distribution of action labels changes substantially.
- The distribution of reason codes changes substantially.
- Input feature distributions change noticeably.
- CTR, impressions, or average position patterns shift.
- The recommendations no longer match what human reviewers observe.

### Retrain / rule-review triggers

A model or rule should be reconsidered when observed performance changes
substantially, the input data changes, or human reviewers repeatedly disagree
with the recommendations.

The baseline should remain transparent and should not be changed simply to
improve a reported metric. Any change should be documented and evaluated again.

### Decision rule

Monitoring is intended to detect stale recommendations. It is a trigger for
human investigation, not an automatic retraining or deployment action.

In [9]:
# ---------------------------------------------------------
# Section 4: Monitoring / Retrain Triggers
# ---------------------------------------------------------

print("=" * 60)
print("MONITORING / RETRAIN TRIGGERS")
print("=" * 60)

# ---------------------------------------------------------
# Current action distribution
# ---------------------------------------------------------

action_distribution = (
    ranked_df["action_label"]
    .value_counts()
    .sort_index()
)

print("\nCURRENT ACTION DISTRIBUTION")
print("-" * 60)

display(action_distribution.to_frame("count"))

# ---------------------------------------------------------
# Current reason-code distribution
# ---------------------------------------------------------

reason_distribution = (
    ranked_df["reason_code"]
    .value_counts()
    .head(10)
)

print("\nTOP REASON CODES")
print("-" * 60)

display(reason_distribution.to_frame("count"))

# ---------------------------------------------------------
# Monitoring checks
# ---------------------------------------------------------

monitoring_checks = [
    "Action-label distribution changes substantially.",
    "Reason-code distribution changes substantially.",
    "Input feature distributions change noticeably.",
    "CTR, impressions, or average-position patterns shift.",
    "Human reviewers repeatedly disagree with recommendations."
]

print("\nMONITORING TRIGGERS")
print("-" * 60)

for number, trigger in enumerate(monitoring_checks, start=1):
    print(f"{number}. {trigger}")

# ---------------------------------------------------------
# Retrain / rule-review checks
# ---------------------------------------------------------

retrain_checks = [
    "Observed performance changes substantially.",
    "The input data or available signals change.",
    "Human reviewers repeatedly identify incorrect recommendations."
]

print("\nRETRAIN / RULE-REVIEW TRIGGERS")
print("-" * 60)

for number, trigger in enumerate(retrain_checks, start=1):
    print(f"{number}. {trigger}")

# ---------------------------------------------------------
# Final monitoring requirement
# ---------------------------------------------------------

print("\n" + "=" * 60)
print("MONITORING DECISION")
print("=" * 60)

print(
    "PASS: Monitoring triggers are defined for stale or changing recommendations."
)

print(
    "Monitoring triggers human investigation; they do not automatically retrain "
    "or deploy a new model."
)

============================================================
MONITORING / RETRAIN TRIGGERS
============================================================

CURRENT ACTION DISTRIBUTION
------------------------------------------------------------

                     count
action_label
Monitor              15820
No Action             2525
Refresh Immediately   1338
Review Soon          10317

TOP REASON CODES
------------------------------------------------------------

                                          count
reason_code
LOW_CTR                                   14373
LOW_CTR; POOR_POSITION                     6694
HIGH_IMPRESSIONS; LOW_CTR                  3547
NONE                                       2525
HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION   1338
HIGH_IMPRESSIONS                           1016
POOR_POSITION                               431
HIGH_IMPRESSIONS; POOR_POSITION              76

MONITORING TRIGGERS
------------------------------------------------------------
1. Action-label distribution changes substantially.
2. Reason-code distribution changes substantially.
3. Input feature distributions change noticeably.
4. CTR, impressions, or average-position patterns shift.
5. Human reviewers repeatedly disagree with recommendations.

RETRAIN / RULE-REVIEW TRIGGERS
------------------------------------------------------------
1. Observed performance changes substantially.
2. The input data or available signals change.
3. Human reviewers repeatedly identify incorrect recommendations.

============================================================
MONITORING DECISION
============================================================
PASS: Monitoring triggers are defined for stale or changing recommendations.
Monitoring triggers human investigation; they do not automatically retrain or deploy a new model.

## 5. Exports for the paper

*Write the queue (and any figures you want to reuse) to work/outputs/ — your paper builds on these files.*

### Exports for the Paper

The ranked action queue is exported so it can be reused in the research paper.

The export contains the content identifier, action score, reason code, and
recommended action. These fields provide a transparent record of how pages
were prioritized.

The exported queue is a decision-support artifact for human review. It is not
a production automation output.

In [10]:
# ---------------------------------------------------------
# Section 5: Exports for the Paper
# ---------------------------------------------------------

import os
import pandas as pd

print("=" * 60)
print("EXPORTS FOR THE PAPER")
print("=" * 60)

# ---------------------------------------------------------
# Create output directory
# ---------------------------------------------------------

output_dir = "../../work/outputs"

os.makedirs(output_dir, exist_ok=True)

# ---------------------------------------------------------
# Prepare the ranked action queue
# ---------------------------------------------------------

export_columns = [
    "content_id",
    "action_score",
    "reason_code",
    "action_label"
]

export_queue = ranked_df[export_columns].copy()

# Add rank for easier review
export_queue.insert(
    0,
    "rank",
    range(1, len(export_queue) + 1)
)

# ---------------------------------------------------------
# Save the ranked queue
# ---------------------------------------------------------

output_path = os.path.join(
    output_dir,
    "action_playbook_queue.csv"
)

export_queue.to_csv(
    output_path,
    index=False
)

# ---------------------------------------------------------
# Verify the export
# ---------------------------------------------------------

print("\nExport path:")
print(output_path)

print("\nRows exported:", len(export_queue))

print("\nColumns exported:")
print(list(export_queue.columns))

print("\nFirst 10 exported actions:")
display(export_queue.head(10))

# ---------------------------------------------------------
# Confirm that the file exists
# ---------------------------------------------------------

if os.path.exists(output_path):
    print("\nPASS: Ranked action queue exported successfully.")
else:
    print("\nWARNING: Export file was not created.")

============================================================
EXPORTS FOR THE PAPER
============================================================

Export path:
../../work/outputs\action_playbook_queue.csv

Rows exported: 30000

Columns exported:
['rank', 'content_id', 'action_score', 'reason_code', 'action_label']

First 10 exported actions:

,rank,content_id,action_score,reason_code,action_label
0,1,content_2cb567c3c89b,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
1,2,content_2dba2b1f9536,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
2,3,content_b28d1efd668f,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
3,4,content_813e88069237,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
4,5,content_ff94c9b6b411,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
5,6,content_66b4046cc144,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
6,7,content_a023517539fe,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
7,8,content_b511d4bc4ad2,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
8,9,content_f02b48f88241,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately
9,10,content_05e9b4cd9ccf,3,HIGH_IMPRESSIONS; LOW_CTR; POOR_POSITION,Refresh Immediately

PASS: Ranked action queue exported successfully.

## Self-check

Before you submit, confirm each line honestly:

- [x] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [x] No client names, URLs, or private queries anywhere
- [x] My claims use careful words: observed, measured, directional, decision-support
- [x] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.